#!/usr/bin/perl6

my $name = "\c[GUJARATI LETTER JA]\c[GUJARATI LETTER LA]\c[GUJARATI LETTER DHA]\c[GUJARATI LETTER RA] \c[GUJARATI LETTER HA]. \c[GUJARATI LETTER VA]\c[GUJARATI SIGN VIRAMA]\c[GUJARATI LETTER YA]\c[GUJARATI VOWEL SIGN AA]\c[GUJARATI LETTER SA]";

say $name;
